### ISSUE TITLE
Resolver  a mensagem de erro com script extrator

### ISSUE THREAD

**Issue by isfttr** [isfttr/VarysNupitec#1]
Aparecendo a seguinte mensagem de erro:

Execução
```bash
python3 extrator.py

# Output

/Users/lucasaguiar/.pyenv/versions/3.11.8/lib/python3.11/site-packages/scrapy/utils/request.py:254: ScrapyDeprecationWarning: '2.6' is a deprecated value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting.

It is also the default value. In other words, it is normal to get this warning if you have not defined a value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting. This is so for backward compatibility reasons, but it will change in a future version of Scrapy.

See the documentation of the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting for information on how to handle this deprecation.
  return cls(crawler)
/Users/lucasaguiar/.pyenv/versions/3.11.8/lib/python3.11/site-packages/scrapy/utils/request.py:254: ScrapyDeprecationWarning: '2.6' is a deprecated value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting.

It is also the default value. In other words, it is normal to get this warning if you have not defined a value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting. This is so for backward compatibility reasons, but it will change in a future version of Scrapy.

See the documentation of the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting for information on how to handle this deprecation.
  return cls(crawler)
Error caught on signal handler: <bound method TelnetConsole.stop_listening of <scrapy.extensions.telnet.TelnetConsole object at 0x123070d10>>
Traceback (most recent call last):
  File "/Users/lucasaguiar/.pyenv/versions/3.11.8/lib/python3.11/site-packages/scrapy/utils/defer.py", line 348, in maybeDeferred_coro
    result = f(*args, **kw)
  File "/Users/lucasaguiar/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/Users/lucasaguiar/.pyenv/versions/3.11.8/lib/python3.11/site-packages/scrapy/extensions/telnet.py", line 77, in stop_listening
    self.port.stopListening()
AttributeError: 'TelnetConsole' object has no attribute 'port'
N° de processo BR 10 2024 004569 6, resultados ['', '', '200', '', '', '2.10', 'Documentos Publicados']
Exigências encontradas para a proteção BR 10 2024 004569 6: 
Análises Substitutivas:  - EXAME TÉCNICO AUSENTE!!! -

Documento corrompido:  Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl. 

```

Dependência está instalada:

```bash
conda list | grep openpyxl

# output

openpyxl                  3.0.10          py311h80987f9_0  
```

**Comment by isfttr** [comment]
Por meio do codespaces é possível `pip install openpyxl` e resolveu os problemas.
